%% Derivative of G towards the plane elements
% Calculates the derivateive of G with respect towards the two components
% that are describing the plane
%% 
function  DGDxv = DGdx(xv, x_p, y_p, z_p,...
    vx_p, vy_p, vz_p, wobj_1, wobj_2, dw1dx, dw2dx, ...
    ix_x_relevant, ix_y_relevant, ix_z_relevant, iv_x_relevant,...
    iv_y_relevant, iv_z_relevant, obj_weights)


w_x = obj_weights(1);
w_y = obj_weights(2);
w_z = obj_weights(3);
w_vx = obj_weights(4);
w_vy = obj_weights(5);
w_vz = obj_weights(6);


DGDxv = w_x*2*(wobj_1*xv(ix_x_relevant(1))...
    + wobj_2*xv(ix_x_relevant(2)) - x_p)...
    *(dw1dx*xv(ix_x_relevant(1)) + wobj_1 + dw2dx*xv(ix_x_relevant(2)))...
    +w_y*2*(wobj_1*xv(ix_y_relevant(1)) + wobj_2*xv(ix_y_relevant(2)) - y_p)*...
    (dw1dx*xv(ix_y_relevant(1))+dw2dx*xv(ix_y_relevant(2)))...
    +w_z*2*(wobj_1*xv(ix_z_relevant(1)) + wobj_2*xv(ix_z_relevant(2)) - z_p)*...
    (dw1dx*xv(ix_z_relevant(1))+dw2dx*xv(ix_z_relevant(2)))...
    +w_vx*2*(wobj_1*xv(iv_x_relevant(1)) + wobj_2*xv(iv_x_relevant(2)) - vx_p)*...
    (dw1dx*xv(iv_x_relevant(1))+dw2dx*xv(iv_x_relevant(2)))...  
    +w_vy*2*(wobj_1*xv(iv_y_relevant(1)) + wobj_2*xv(iv_y_relevant(2)) - vy_p)*...
    (dw1dx*xv(iv_y_relevant(1))+dw2dx*xv(iv_y_relevant(2)))...
    +w_vz*2*(wobj_1*xv(iv_z_relevant(1)) + wobj_2*xv(iv_z_relevant(2)) - vz_p)*...
    (dw1dx*xv(iv_z_relevant(1))+dw2dx*xv(iv_z_relevant(2)));


end